# Generated by Django 4.2.6 on 2023-10-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnulinux', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
