# Generated by Django 4.2.6 on 2023-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnulinux', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Класс CSS'),
        ),
    ]
